language: python
python:
- '3.5'
install: pip install -r requirements.txt
script: python test.py -v
deploy:
  provider: heroku
  api_key:
    secure: MMzyJ42hoBwAGJ+QoyFEOmlkGI9yOpmYUZ5hws+Wv9cXT/eZZ8UP+WenQ0yJfCiDsvxS91YUjwdVRI2tHWxN868PeCJwjgtfjkA4zg2t0eZbu03/HtHpvKAEIgwHqkacIRAaQVrMbWJQLqK0ReNsNbrISQvyxELE3BQoX97gqczT72g+SluIdslCgn3V9DEZM5BJ1dIk+f1akmihjel3Ai32tYDoap50yizaEFCTIZHy/rqS+V/+X6KriSD1UI4Bu/qvcfZAs2gN6d7FPsrrKMmOGiOCu7uFdz7y9Rfrh/08dts/SKwZssXo8GVI1EszHjdAdf5Obpiueg6OGg+CclDh90BPIoQ62CyS/6UmnVynDuP11KOjyoVNOvNDBA+omRxv6plm2YgwGzNeMwnCz5IHujN7vUO+pv6lEmsPWnF/pq906e7AHde1plOMx3qKE6nZB0AgfyI25pQlbUHqcFcRPBgC6k0tioWbPLssS/Sg1obmieKm5MQEbh/6UqoW0YdkG9f8TufQfMpwmNPi6VkOr3XBUO32AURlWp2ZATTyjhwYnufPd41d6qd0WuaP5PO5G4Dson9iiv1aBcGUfKUKid4bRqrXCcslDkIobUOucc22zx1LGUj4RJRz4z17lsaiW7fg5qKJ+93gJ2HD52uCC9b+OycQp83N5OzuHhU=
  app: Peer-Reviewer-Application
  on:
    repo: akashgrana25/Peer-Reviewer-Application
