language: python
python:
- '3.5'
install: pip install -r requirements.txt
script: python test.py -v
deploy:
  provider: heroku
  api_key:
    secure: emq0cXoFS+Gq+vMyFzdG97H2Yi7Fe3BOrbnBoRUmGMcKzVa/OFFI7/dJrGHZ7L0Yy58u+sjc+lEPI3W/k9D1+JgF3yvoJFEcJTCeiXDZJvBiBIse2+qfpCn5yzZvFndplm7V2XBrBR+QuXnU+1gx8lCdhMzfj4TtW9PkFH1Q0s+8OPLRzlwFkLLe2VKB5lGdbnHW1STpI5vFUuUBuL2XoEdgLlOyqTxMT5aE5Std69onZT6TqFZ0IRPp+4wUKlnWGTE1q7hhFp1U0wt3s4fuwo4I3lYT0hzSRU9At+jFUeibZTrJ3yV2u44YFEqI4HLDpdZTNwWId+Xb25G8UPZ3SrJz3SbChA7x9cxG/Q6mgJd9OEddN0iFVZAJ+C+vOZzCt62K4j61EWkgKK0iYNaJ7kiR/9tFxTmtDu0qAMyU3HQQih4LbVGi2MDl1PuHo4jGzzZI3hWkgvVxdrlS/AJ69itrZVKgRS5k9kWzCJztE48IJ2moXOoBFeEhkO13efgwY0dyzAp04E9qNEuywseojJ65OzXCA4bPbTgTe4i9LA6n6WZZFamKSr4DPB3/xgh6+wna0Hv6BlxTfKnxdKXq+BUqH2y+P4k59kYC00719KhFEJMtquXjuMaCQrqeeY5lC8V5QanYCfXlC44ZHp4aNrW9cPVqFvg/7uySDRdzL7c=
  app: Peer-Reviewer-Application
  on:
    repo: akashgrana25/Peer-Reviewer-Application
