language: python
python:
- '3.5'
install: pip install -r requirements.txt
script: python test.py -v
deploy:
  provider: heroku
  api_key:
    secure: TE8OXUaCiJt7Dr3GxyeCn1yrwqzHixu2x2Q2jk5pBQQx121N+oOxLjt4v0fNeNp+lPcXWC64AFWt/shdXCUf9ScaOqKmn1+VMyj2lnt7/VyYVw1am2nAFYPopPklUa1qJ4rTGqk1qqP9LZ1AFSBfm9t2iY9tw696WKXkJpLY3rmz0mv9KTPUWOUWhKoIE5cEMSeQ2USrvFvB4NQTj8wVAPbIAOsvL22IsVOw9edbD7IxdeMYCp9doQQpE2FTnxDqgZl3prcKNrnTo5bdU8XpM3LP0M3cwHTcrIAJqBP1TUXFqCM9is4vb1UnSNuDP0gzaPGl9yF6cE2Nkm23RZPdBhIHNjLw1EJ1LHpG0uLTZOtSbF5C+1qPf0UXUFVPOC082CUnHCE4GKe48U1Yjok0sc4K1Hun1y3My1OwLVqCKTjcJegaXNL4cQUrb32wWpn28mMmp1CD/23dyqnzprRSx4hKFPoGX8gXI/5JkklC4EJDEeGU3QjWnl1nhzRJ1/3rB7r3pzcmgZam8iXi33+SXEScXAM0HgCNN+LS2oRz4n4YAYnAM+xy4egQuueibzWVZkhdSST8r0f+g+vI5kUS9Wq+YnpmIMvLPuqgdu2qih2uJwS7HjdSAghb2tNR5cYusqJ+e2GfI9/qLoFpz7AEj01p4tZpkXIB7vrYozBjhcc=
  app: peer-reviewer-application
  on:
    repo: akashgrana25/Peer-Reviewer-Application
